import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'EN' | 'KN' | 'SW' | 'FR';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    EN: {
        // Navigation & Common
        home: 'Home',
        about: 'About Us',
        programs: 'Programs',
        testimonials: 'Testimonials',
        contact: 'Contact Us',
        join_us: 'Join Us',
        sign_in: 'Sign In',
        sign_up: 'Sign Up',
        sign_out: 'Sign Out',
        dashboard: 'Dashboard',
        profile: 'Profile',
        bookings: 'My Bookings',
        account_settings: 'Account Settings',
        control_dashboard: 'Control Dashboard',
        manage_bookings: 'Manage Bookings',
        our_story: 'Our Story',
        our_team: 'Our Team',
        partners: 'Partners',
        social_impact: 'Social Impact',
        help_center: 'Help Center',
        who_we_are: 'Who We Are',
        our_network: 'Our Network',
        support: 'Support',
        core_services: 'Our Core Services',
        highlights: 'Highlights',
        events: 'Me For You Events',
        housing: 'Me For You Housing',
        transport: 'Me For You Transport',
        cultural: 'Cultural Programs',
        upcoming: 'UPCOMING',
        new: 'NEW',
        currency: 'Currency',
        view_details: 'View Details',
        book_now: 'Book Now',

        // Home Page
        hero_title_1: 'Premium Services for Your Needs',
        hero_desc_1: 'Your trusted partner for unforgettable events, reliable car rentals, and comfortable accommodations in Rwanda.',
        hero_title_2: 'Everything You Need In One Place',
        hero_desc_2: 'From planning to execution, we handle everything so you can enjoy the moment with peace of mind.',
        hero_title_3: 'Memorable Cultural Experiences',
        hero_desc_3: 'Discover the rich history and traditions of Rwanda through our guided tours and community events.',
        hero_title_4: 'Comfortable Stays in Kigali',
        hero_desc_4: 'Secure and fully-furnished housing solutions tailored for your business or personal stay in the heart of Rwanda.',
        why_choose_us: 'Why Choose Us',
        why_choose_us_desc: 'We are dedicated to making your special events memorable and providing top-quality rental services for your convenience in Rwanda.',
        expert_team: 'Expert Team',
        expert_team_desc: 'Our professional team brings years of experience to ensure excellence in every project we undertake.',
        guaranteed_quality: 'Guaranteed Quality',
        guaranteed_quality_desc: 'We prioritize quality and customer satisfaction above all, maintaining the highest service standards.',
        client_centric: 'Client Centric',
        client_centric_desc: 'Your needs are our priority. We offer tailors solutions that perfectly match your expectations.',
        premium_services: 'Our Premium Services',
        premium_services_desc: 'Discover a wide range of services designed to make your life easier and your events more spectacular.',
        what_clients_say: 'What Our Clients Say!',
        ready_to_hire: 'Ready to Hire Us for Your Event?',
        ready_to_hire_desc: "Call us today or visit our office to discuss your project. We're ready to make your vision come to life.",

        // Mobile App Section
        mobile_app_title: 'Me For You Mobile Apps',
        mobile_app_subtitle: 'Enhance Your Booking Experience',
        mobile_app_desc: 'Offer a complete digital experience with feature-rich Me For You mobile apps for Android and iOS platforms. Manage your event bookings, check vehicle availability, and find accommodations on the go.',
        mobile_app_android_ios: 'Android and iOS Apps',
        mobile_app_feature_desc: 'The app engages users with an intuitive interface, logical workflows, interactive functionality, and robust performance.',
        explore_more: 'Explore More',
        supercharge_success: 'Supercharge your Success with Best-in-Class Mobile Apps',

        // Process Section
        process_title: 'Project Planning & Execution Process',
        process_subtitle: 'How We Deliver Excellence for Every Client',
        process_desc: 'We follow a structured methodology to ensure your events, housing needs, and transport requirements are handled with professional precision.',

        stage_1: 'Consultation',
        stage_1_p1: 'Initial Briefing',
        stage_1_p2: 'Site Visitation',
        stage_1_p3: 'Budget Analysis',
        stage_1_p4: 'Needs Assessment',
        stage_2: 'Strategy',
        stage_2_p1: 'Venue Selection',
        stage_2_p2: 'Vendor Networking',
        stage_2_p3: 'Theme Design',
        stage_2_p4: 'Timeline Management',
        stage_3: 'Execution',
        stage_3_p1: 'Decor Implementation',
        stage_3_p2: 'Logistics Coordination',
        stage_3_p3: 'Service Quality Check',
        stage_3_p4: 'Live Monitoring',
        stage_4: 'Final Delivery',
        stage_4_p1: 'Event Success',
        stage_4_p2: 'Feedback Collection',
        stage_4_p3: 'Post-Event Support',
        stage_4_p4: 'Long-term Partnership',

        lets_work_together: "Let's Work Together",

        // FAQ Section
        faq_title: 'Frequently Asked Questions',
        faq_q1: 'Do I need to pay upfront for event planning services?',
        faq_a1: 'We typically require a commitment deposit to secure vendors and your preferred date. The remaining balance can be settled according to a milestone-based payment schedule discussed during your consultation.',
        faq_q2: 'Can I rent a car without a professional driver?',
        faq_a2: 'Yes, we offer self-drive options for most of our fleet. You will need to provide a valid driving permit and a security deposit. Alternatively, our professional drivers are available for a stress-free experience.',
        faq_q3: 'What are the requirements for long-term house rentals?',
        faq_a3: 'For long-term stays (3+ months), we require a signed lease agreement and a one-month security deposit. All our properties come fully furnished with utilities and security included.',
        faq_q4: 'How can I track the status of my booking?',
        faq_a4: 'Once you log in to your Me For You account, you can access the "My Bookings" dashboard. Here you can see real-time updates on your request status, payment history, and assigned service managers.',
        faq_q5: 'Do you support international credit card payments?',
        faq_a5: 'Absolutely. We accept all major credit/debit cards (Visa, MasterCard), as well as local Mobile Money (MTN MoMo, Airtel Money) and direct bank transfers.',

        // Dashboard & Bookings
        recent_activity: 'Recent Activity',
        view_all: 'View All',
        no_bookings: 'No recent bookings found.',
        book_first: 'Book Your First Service',
        quick_actions: 'Quick Actions',
        plan_event: 'Plan an Event',
        rent_vehicle: 'Rent a Vehicle',
        find_house: 'Find a House',
        total_bookings: 'Total Bookings',
        pending: 'Pending',
        confirmed: 'Confirmed',
        total_spent: 'Total Spent',
        revenue: 'Revenue',
        id: 'ID',
        service: 'Service',
        date: 'Date',
        amount: 'Amount',
        status: 'Status',
        completed: 'Completed',
        cancelled: 'Cancelled',
        paid: 'Paid',
        estimated_total: 'Estimated Total',

        // Car & House Rental
        rental_duration: 'Rental Duration',
        pickup_date: 'Pickup Date',
        return_date: 'Return Date',
        checkin_date: 'Check-in Date',
        checkout_date: 'Check-out Date',
        seats: 'Seats',
        category: 'Category',
        select_vehicle: 'Select Vehicle',
        select_property: 'Select Property',
        stay_details: 'Stay Details',
        find_home: 'Find Your Home Away From Home',
        premium_fleet: 'Our Premium Fleet',

        // About Us Detailed Content
        mission_title: 'Our Mission',
        mission_desc: 'At Me For You Advisory, our mission is to make your life easier, your celebrations unforgettable, and your journeys stress-free. We achieve this by providing world-class services in Events, Housing, and Transport, executed with precision, creativity, and care. Our goal is to deliver seamless, professional, and personalized solutions that exceed your expectations every time.',
        background_title: 'Who We Are',
        background_desc: 'Me For You Advisory is your professional companion for Events, Housing, and Transport. We transform ideas into experiences and challenges into solutions. With a commitment to professionalism, trustworthiness, and smartness, we provide services that make your life easier, your events memorable, and your plans worry-free. Whether planning a wedding, finding your ideal home, or arranging reliable transport, we ensure that every experience is seamless, enjoyable, and tailored to your needs.',
        founder_quote: 'We are driven by practical outcomes that create meaningful impact. Our focus is on delivering real, measurable results that make a difference in people’s lives and organizations’ success.',
        founder_full_name: 'Papy Patrick Ndazigaruye',
        value_professionalism: 'Professionalism',
        value_professionalism_desc: 'We execute every task with skill, attention to detail, and respect, ensuring top-quality service across all our programs.',
        value_trustworthiness: 'Trustworthiness',
        value_trustworthiness_desc: 'We honor our commitments, protect your interests, and maintain transparency in everything we do.',
        value_smartness: 'Smartness',
        value_smartness_desc: 'We bring creative, efficient, and innovative solutions that save you time, effort, and resources while delivering maximum impact.',

        // Footer
        get_in_touch: 'Get In Touch',
        quick_links: 'Quick Links',
        photo_gallery: 'Photo Gallery',
        hints_links: 'Hints & Links',
        all_rights_reserved: 'All Right Reserved.',
        privacy_policy: 'Privacy Policy',
        terms_condition: 'Terms & Condition',

        // Forms
        full_name: 'Full Name',
        email: 'Email Address',
        password: 'Password',
        login_btn: 'Login',
        register_btn: 'Create Account',
        forgot_password: 'Forgot Password?',
        have_account: 'Already have an account?',
        no_account: "Don't have an account?",
        phone_number: 'Phone Number'
    },
    KN: {
        // Navigation & Common
        home: 'Ahabanza',
        about: 'About Us',
        programs: 'Programu',
        testimonials: 'Ubuhamya',
        contact: 'Twandikire',
        join_us: 'Twiyungeho',
        sign_in: 'Injira',
        sign_up: 'Kwiyandikisha',
        sign_out: 'Sohoka',
        dashboard: 'Dashboard',
        profile: 'Umwirondoro',
        bookings: 'Ibyo nategetse',
        account_settings: 'Igenamiterere',
        control_dashboard: 'Imenyekanisha',
        manage_bookings: 'Gucunga amashuri',
        our_story: 'Amateka yacu',
        our_team: 'Ikipe yacu',
        partners: 'Abafatanyabikorwa',
        social_impact: 'Ibikorwa remezo',
        help_center: 'Ubufasha',
        who_we_are: 'Twebwe abo turi bo',
        our_network: 'Ihuriro ryacu',
        support: 'Ubufasha',
        core_services: 'Serivisi duna',
        highlights: 'Ibyingenzi',
        events: 'Ibirori',
        housing: 'Inzu',
        transport: 'Guherekeza',
        cultural: 'Umuco',
        upcoming: 'BIRAZA',
        new: 'GISHYA',
        currency: 'Ifaranga',
        view_details: 'Reba Ibisobanuro',
        book_now: 'Tegeka None',

        // Home Page
        hero_title_1: 'Serivisi Nziza ku Keneye Zawe',
        hero_desc_1: 'Umufatanyabikorwa wawe wizewe mu birori bitazibagirana, gukodesha imodoka zizewe, n’amacumbi meza mu Rwanda.',
        hero_title_2: 'Ibyo Ukeneye Byose mu Karere Kamwe',
        hero_desc_2: 'Kuva mu itegura kugeza mu ishyirwa mu bikorwa, duca mu byose kugira ngo ushobore kwishimira akanya mu mutuzo.',
        hero_title_3: 'Ibirori by’Umuco Bitazibagirana',
        hero_desc_3: 'Vumbura amateka n’imigenzo ikize y’u Rwanda binyuze mu ngendo zacu n’ibirori by’abaturage.',
        hero_title_4: 'Amacumbi Meza i Kigali',
        hero_desc_4: 'Amacumbi arinzwe kandi afite ibikoresho byose agenewe ubushabitsi cyangwa kuguma kwawe mu mutima w’u Rwanda.',
        why_choose_us: 'Kuki Wahitamo Twebwe',
        why_choose_us_desc: 'Twiyemeje gutuma ibirori byawe byihariye biba ibitazibagirana kandi dutanga serivisi zo gukodesha zo mu rwego rwo hejuru kugira ngo umererwe neza mu Rwanda.',
        expert_team: 'Ikipe y’Abahanga',
        expert_team_desc: 'Ikipe yacu y’ababigize umwuga izana uburambe bw’imyaka myinshi kugira ngo ihakane ubuziranenge muri buri mushinga dukora.',
        guaranteed_quality: 'Ubuziranenge Bwizewe',
        guaranteed_quality_desc: 'Dushyira ubuziranenge n’umunezero w’umukiriya imbere y’ibindi byose, tugumana urwego rwo hejuru rwa serivisi.',
        client_centric: 'Umukiriya ku ntebe y’Imbere',
        client_centric_desc: 'Ibikenerwa byawe nibyo dushyira imbere. Dutanga ibisubizo bikwiye neza ibyo witeze.',
        premium_services: 'Serivisi Zacu Zo mu Rwego rwo Hejuru',
        premium_services_desc: 'Vumbura serivisi nyinshi zagenewe kukubohora mu buzima no gutuma ibirori byawe biba bitangaje.',
        what_clients_say: 'Ibyo Abakiriya Bacu Bavuga!',
        ready_to_hire: 'Witeguye Kutubikira ku Birori Byawe?',
        ready_to_hire_desc: 'Duhamagare uyu munsi cyangwa usure ibiro byacu kugira ngo tuganire ku mushinga wawe. Twiteguye gutuma icyerekezo cyawe kiba impamo.',

        // Mobile App Section
        mobile_app_title: 'Programu ya Me For You ya Terefoni',
        mobile_app_subtitle: 'Horanya uburambe bwiza bwo gutumiza',
        mobile_app_desc: 'Tanga uburambe bwuzuye bwa digitale hamwe n’urwego rwo hejuru rwa gahunda ya Me For You kuri terefoni za Android na iOS. Cunga ibyo wategetse, reba niba imodoka zihari, kandi ushake amacumbi aho waba uri hose.',
        mobile_app_android_ios: 'Porogaramu za Android na iOS',
        mobile_app_feature_desc: 'Porogaramu yubaka umubano n’abakoresha binyuze mu buryo bworoshye bwo gukoresha, imikorere isobanutse, n’umuvuduko mwinshi.',
        explore_more: 'Vumbura Byinshi',
        supercharge_success: 'Ongera intsinzi yawe hamwe na porogaramu za terefoni nziza cyane',

        // Process Section
        process_title: 'Uburyo dutegura kandi tukanashyira mu bikorwa imishinga',
        process_subtitle: 'Uko duha abakiriya bacu serivisi nziza',
        process_desc: 'Dukurikiza uburyo bunoze kugira ngo tumenye neza ko ibirori byawe, inzu ukeneye, n’uburyo bwo kwerekeza byose bikorwa mu buryo bwa kinyamwuga.',

        stage_1: 'Inama',
        stage_1_p1: 'Iganira ry’ibanze',
        stage_1_p2: 'Gusura aho umushinga uzakorerwa',
        stage_1_p3: 'Isuzuma ry’ingengo y’imari',
        stage_1_p4: 'Isuzuma ry’ibikenewe',
        stage_2: 'Ingamba',
        stage_2_p1: 'Guhitamo aho ibirori bizabera',
        stage_2_p2: 'Gushaka abashoramari',
        stage_2_p3: 'Gutegura imitako',
        stage_2_p4: 'Gucunga igihe',
        stage_3: 'Ikurikiranabikorwa',
        stage_3_p1: 'Gushyira mu bikorwa imitako',
        stage_3_p2: 'Gukurikirana ibikoresho',
        stage_3_p3: 'Isuzumwa ry’ubuziranenge',
        stage_3_p4: 'Gukurikirana amasegonda ku yandi',
        stage_4: 'Isoswa ry’umushinga',
        stage_4_p1: 'Intsinzi y’ibirori',
        stage_4_p2: 'Gukusanya ibitekerezo',
        stage_4_p3: 'Ubufasha nyuma y’umushinga',
        stage_4_p4: 'Ubufatanyabikorwa bw’igihe kirekire',

        lets_work_together: "Reka dukorane",

        // FAQ Section
        faq_title: 'Ibibazo Bikunze Kubazwa',
        faq_q1: 'Ese ngomba kwishyura mbere yo gutegurirwa ibirori?',
        faq_a1: 'Abenshi bishyura avansi yo gufata aho ibirori bizabera n’abakozi. Amafaranga asigaye yishyurwa hakurikijwe amasezerano tugirana igihe cy’inama yacu ya mbere.',
        faq_q2: 'Ese nshobora gukodesha imodoka ntwaye?',
        faq_a2: 'Yego, dufite imodoka ushobora kwitwara. Ugomba kuba ufite uruhushya rwo gutwara ruriho n’ingwate. Ushobora no gufata umushoferi wacu w’umwuga kugira ngo uruhuke.',
        faq_q3: 'Ni ibiki bikenewe mu gukodesha inzu igihe kirekire?',
        faq_a3: 'Ku bantu bamara amezi 3 cyangwa arenga, dukora amasezerano yo gukodesha kandi ugatanga ingwate y’ukwezi kumwe. Inzu zacu zifite ibikoresho byose, umuriro, amazi n’umutekano.',
        faq_q4: 'Nakurikirana nte uko gutumiza kwanjye guhagaze?',
        faq_a4: 'Iyo winjiye muri konti yawe ya Me For You, ushobora kubona ibyo wategetse byose. Uzabonamo uko bihagaze, uko wishyuye, n’umukozi ushinzwe kugufasha.',
        faq_q5: 'Ese mwakira amakarita yo kwishyura mpuzamahanga?',
        faq_a5: 'Yego rwose. Twakira amakarita yose azwi (Visa, MasterCard), Mobile Money (MTN MoMo, Airtel Money) ndetse no kohereza kuri banki.',

        // Dashboard & Bookings
        recent_activity: 'Ibikorwa biheruka',
        view_all: 'Reba byose',
        no_bookings: 'Nta byo wategetse bihari.',
        book_first: 'Tegeka serivisi ya mbere',
        quick_actions: 'Ibyo wagura vuba',
        plan_event: 'Tegura ibirori',
        rent_vehicle: 'Kodesha imodoka',
        find_house: 'Shaka inzu',
        total_bookings: 'Byose nategetse',
        pending: 'Bitegerejwe',
        confirmed: 'Byemejwe',
        total_spent: 'Ayakoreshejwe yose',
        revenue: 'Inyungu',
        id: 'ID',
        service: 'Serivisi',
        date: 'Itariki',
        amount: 'Amafaranga',
        status: 'Imiterere',
        completed: 'Byarangiye',
        cancelled: 'Byasheshwe',
        paid: 'Byishyuwe',
        estimated_total: 'Igiciro mberacyo',

        // Car & House Rental
        rental_duration: 'Igihe cyo gukodesha',
        pickup_date: 'Itariki yo gufata',
        return_date: 'Itariki yo kugarura',
        checkin_date: 'Itariki yo kwinjira',
        checkout_date: 'Itariki yo gusohoka',
        seats: 'Ibyicaro',
        category: 'Icyiciro',
        select_vehicle: 'Hitamo imodoka',
        select_property: 'Hitamo inzu',
        stay_details: 'Ibisobanuro byo kuhaba',
        find_home: 'Shaka amacumbi akubereye',
        premium_fleet: 'Imodoka zacu nziza',

        // About Us Detailed Content
        mission_title: 'Inshingano Zacu',
        mission_desc: 'Muri Me For You Advisory, inshingano yacu ni ukububorohereza ubuzima, gutuma ibirori byanyu biba ibitazibagirana, n\'ingendo zanyu zikaba ntamupaka. Tubigeraho dutanga serivisi zo mu rwego rw\'isi mu birori, amazu, n’uburyo bwo kwerekeza, bikozwe n’ubuhanga, guhanga udushya, n’ubwitonzi. Intego yacu ni ugutanga ibisubizo binoze, bya kinyamwuga, kandi byihariye birenze ibyo mwitegura buri gihe.',
        background_title: 'Twebwe abo turi bo',
        background_desc: 'Me For You Advisory ni umufatanyabikorwa wawe wa kinyamwuga mu birori, amazu, n’uburyo bwo kwerekeza. Duhindura ibitekerezo mo ubuhamya n\'inzitane mo ibisubizo. Twiyemeje kugaragaza ubunyamwuga, kwizerwa, n\'ubwenge, dutanga serivisi zoroshya ubuzima bwawe, zigatuma ibirori byawe bitazibagirana, kandi n\'imigambi yawe ikaba idafite impungenge. Waba utegura ubukwe, ushaka inzu yawe nziza, cyangwa upanga urugendo rwizewe, twemeza ko buri kintu cyose kigenda neza, gishimishije, kandi gihuye n\'ibyo ukeneye.',
        founder_quote: 'Dutwarwa n\'ibisubizo bifatika bitanga impinduka zifatika. Icyo dushyize imbere ni ugutanga ibisubizo nyabyo, bishobora gupimwa, bitanga itandukaniro mu mibereho y\'abantu no mu ntsinzi y\'ibigo.',
        founder_full_name: 'Papy Patrick Ndazigaruye',
        value_professionalism: 'Ubunyamwuga',
        value_professionalism_desc: 'Dusohoza buri nshingano yose n\'ubuhanga, kwitondera ibisobanuro byose, n\'icyubahiro, twemeza serivisi yo mu rwego rwo hejuru muri gahunda zacu zose.',
        value_trustworthiness: 'Kwizerwa',
        value_trustworthiness_desc: 'Wubaha amasezerano yacu, turinda inyungu zawe, kandi tugumana umuseke mu byo dukora byose.',
        value_smartness: 'Ubwenge',
        value_smartness_desc: 'Tuzana ibisubizo byihuse, binoze, kandi bivuguruye bikuzigamira igihe, imbaraga, n’umutungo mugihe bitanga umusaruro ugaragara.',

        // Footer
        get_in_touch: 'Twandikire',
        quick_links: 'Imiyoboro yihuse',
        photo_gallery: 'Amafoto',
        hints_links: 'Inama n\'imiyoboro',
        all_rights_reserved: 'Uburenganzira bwose burasubitswe.',
        privacy_policy: 'Amategeko y\'ibanga',
        terms_condition: 'Amategeko n\'amabwiriza',

        // Forms
        full_name: 'Amazina yose',
        email: 'Imeyili',
        password: 'Ijambo ry\'ibanga',
        login_btn: 'Injira',
        register_btn: 'Fungura konti',
        forgot_password: 'Wibagiwe ijambo ry\'ibanga?',
        have_account: 'Usanzwe ufite konti?',
        no_account: 'Nturagira konti?',
        phone_number: 'Nimero ya terefoni'
    },
    SW: {
        // Navigation & Common
        home: 'Nyumbani',
        about: 'Kuhusu Sisi',
        programs: 'Programu',
        testimonials: 'Ushuhuda',
        contact: 'Wasiliana Nasi',
        join_us: 'Jiunge Nasi',
        sign_in: 'Ingia',
        sign_up: 'Jisajili',
        sign_out: 'Ondoka',
        dashboard: 'Dashibodi',
        profile: 'Wasifu',
        bookings: 'Uhifadhi Wangu',
        account_settings: 'Mipangilio ya Akaunti',
        control_dashboard: 'Dashibodi ya Udhibiti',
        manage_bookings: 'Simamia Uhifadhi',
        our_story: 'Hadithi Yetu',
        our_team: 'Timu Yetu',
        partners: 'Washirika',
        social_impact: 'Athari za Kijamii',
        help_center: 'Kituo cha Msaada',
        who_we_are: 'Sisi ni Nani',
        our_network: 'Mtandao Wetu',
        support: 'Msaada',
        core_services: 'Huduma Zetu Kuu',
        highlights: 'Mambo Muhimu',
        events: 'Matukio',
        housing: 'Nyumba',
        transport: 'Usafiri',
        cultural: 'Programu za Kitamaduni',
        upcoming: 'INAYOKUJA',
        new: 'MPYA',
        currency: 'Sarafu',
        view_details: 'Angalia Maelezo',
        book_now: 'Weka Ahadi Sasa',

        // Home Page
        hero_title_1: 'Huduma za Kisasa kwa Mahitaji Yako',
        hero_desc_1: 'Mshirika wako unayeaminika kwa matukio yasiyosahaulika, ukodishaji wa magari unaoaminika, na malazi ya starehe nchini Rwanda.',
        hero_title_2: 'Kila Kitu Unachohitaji Katika Sehemu Moja',
        hero_desc_2: 'Kutoka kwa kupanga hadi utekelezaji, tunashughulikia kila kitu ili uweze kufurahiya wakati huo kwa amani ya akili.',
        hero_title_3: 'Uzoefu wa Kitamaduni wa Kukumbukwa',
        hero_desc_3: 'Gundua historia tajiri na mila za Rwanda kupitia ziara zetu na matukio ya kijamii.',
        hero_title_4: 'Malazi ya Starehe Kigali',
        hero_desc_4: 'Malazi salama na yenye samani kamili yaliyoundwa kwa ajili ya biashara yako au kukaa kwako binafsi katikati mwa Rwanda.',
        why_choose_us: 'Kwa nini Utuchague Sisi',
        why_choose_us_desc: 'Tumejitolea kufanya matukio yako maalum yawe ya kukumbukwa na kutoa huduma za kukodisha za hali ya juu kwa urahisi wako nchini Rwanda.',
        expert_team: 'Timu ya Wataalam',
        expert_team_desc: 'Timu yetu ya wataalamu inaleta uzoefu wa miaka mingi ili kuhakikisha ubora katika kila mradi tunaoanza.',
        guaranteed_quality: 'Ubora uliohakikishwa',
        guaranteed_quality_desc: 'Tunapa kipaumbele ubora na kuridhika kwa wateja kuliko kitu kingine chochoke, tukizingatia viwango vya juu vya huduma.',
        client_centric: 'Mteja Kwanza',
        client_centric_desc: 'Mahitaji yako ni kipaumbele chetu. Tunatoa suluhisho zinazolingana kabisa na matarajio yako.',
        premium_services: 'Huduma Zetu za Kisasa',
        premium_services_desc: 'Gundua huduma mbalimbali zilizoundwa ili kufanya maisha yako yawe rahisi na matukio yako yawe ya kuvutia zaidi.',
        what_clients_say: 'Wateja Wetu Wanasema Nini!',
        ready_to_hire: 'Tayari kutuajiri kwa Tukio Lako?',
        ready_to_hire_desc: 'Tupigie leo au tembelea ofisi yetu ili kujadili mradi wako. Tuko tayari kufanya maono yako yawe kweli.',

        // Mobile App Section
        mobile_app_title: 'Programu za Simu za Me For You',
        mobile_app_subtitle: 'Boresha Uzoefu Wako wa Uhifadhi',
        mobile_app_desc: 'Toa uzoefu kamili wa kidijitali na programu za simu za Me For You zenye huduma nyingi kwa majukwaa ya Android na iOS. Simamia uhifadhi wa matukio yako, angalia upatikanaji wa magari, na tafuta malazi popote ulipo.',
        mobile_app_android_ios: 'Programu za Android na iOS',
        mobile_app_feature_desc: 'Programu inawashirikisha watumiaji na kiolesura angavu, mtiririko wa kazi wa kimantiki, utendaji wa mwingiliano, na utendaji thabiti.',
        explore_more: 'Gundua Zaidi',
        supercharge_success: 'Ongeza Mafanikio yako na Programu Bora za Simu',

        // Process Section
        process_title: 'Mchakato wa Kupanga na Kutekeleza Miradi',
        process_subtitle: 'Jinsi Tunavyotoa Ubora kwa Kila Mteja',
        process_desc: 'Tunafuata mbinu iliyopangwa ili kuhakikisha matukio yako, mahitaji ya nyumba, na mahitaji ya usafiri yanashughulikiwa kwa usahihi wa kitaalamu.',

        stage_1: 'Ushauri',
        stage_1_p1: 'Maelezo ya Awali',
        stage_1_p2: 'Kutembelea Eneo',
        stage_1_p3: 'Uchambuzi wa Bajeti',
        stage_1_p4: 'Tathmini ya Mahitaji',
        stage_2: 'Mkakati',
        stage_2_p1: 'Uteuzi wa Eneo',
        stage_2_p2: 'Mtandao wa Wauzaji',
        stage_2_p3: 'Ubuni wa Mandhari',
        stage_2_p4: 'Usimamizi wa Muda',
        stage_3: 'Utekelezaji',
        stage_3_p1: 'Utekelezaji wa Mapambo',
        stage_3_p2: 'Uratibu wa Vifaa',
        stage_3_p3: 'Ukaguzi wa Ubora wa Huduma',
        stage_3_p4: 'Usimamizi wa Moja kwa Moja',
        stage_4: 'Uwasilishaji wa Mwisho',
        stage_4_p1: 'Mafanikio ya Tukio',
        stage_4_p2: 'Ukusanyaji wa Maoni',
        stage_4_p3: 'Msaada Baada ya Tukio',
        stage_4_p4: 'Ushirika wa Muda Mrefu',

        lets_work_together: "Tufanye Kazi Pamoja",

        // FAQ Section
        faq_title: 'Maswali Yanayoulizwa Sana',
        faq_q1: 'Je, ninahitaji kulipa mapema kwa huduma za upangaji wa hafla?',
        faq_a1: 'Kwa kawaida tunahitaji amana ya kujitolea ili kupata wauzaji na tarehe unayopendelea. Salio lililosalia linaweza kulipwa kulingana na ratiba ya malipo iliyojadiliwa wakati wa mashauriano yako.',
        faq_q2: 'Je, naweza kukodisha gari bila dereva mtaalamu?',
        faq_a2: 'Ndiyo, tunatoa chaguzi za kujiongoza kwa kundi letu nyingi. Utahitaji kutoa kibali halali cha udereva na amana ya usalama. Vinginevyo, madereva wetu wa kitaalamu wanapatikana kwa uzoefu usio na mkazo.',
        faq_q3: 'Ni mahitaji gani ya ukodishaji wa nyumba za muda mrefu?',
        faq_a3: 'Kwa kukaa kwa muda mrefu (miezi 3+), tunahitaji makubaliano ya kukodisha yaliyotiwa saini na amana ya usalama ya mwezi mmoja. Mali zetu zote zina samani kamili na huduma na usalama vimejumuishwa.',
        faq_q4: 'Ninawezaje kufuatilia hali ya uhifadhi wangu?',
        faq_a4: 'Mara tu unapoingia kwenye akaunti yako ya Me For You, unaweza kufikia dashibodi ya "Uhifadhi Wangu". Hapa unaweza kuona sasisho za muda halisi juu ya hali yako ya ombi, historia ya malipo, na wasimamizi wa huduma uliopangiwa.',
        faq_q5: 'Je, unakubali malipo ya kadi ya mkopo ya kimataifa?',
        faq_a5: 'Kabisa. Tunakubali kadi zote kuu za mkopo/debit (Visa, MasterCard), pamoja na Pesa za Simu za ndani (MTN MoMo, Airtel Money) na uhamishaji wa benki moja kwa moja.',

        // Dashboard & Bookings
        recent_activity: 'Shughuli za Hivi Karibuni',
        view_all: 'Tazama Zote',
        no_bookings: 'Hakuna hivi karibuni uhifadhi uliopatikana.',
        book_first: 'Weka Ahadi Yako ya Kwanza',
        quick_actions: 'Hatua za Haraka',
        plan_event: 'Panga Tukio',
        rent_vehicle: 'Kodi Gari',
        find_house: 'Tafuta Nyumba',
        total_bookings: 'Jumla ya Uhifadhi',
        pending: 'Inasubiri',
        confirmed: 'Imethibitishwa',
        total_spent: 'Jumla Iliyotumika',
        revenue: 'Mapato',
        id: 'ID',
        service: 'Huduma',
        date: 'Tarehe',
        amount: 'Kiasi',
        status: 'Hali',
        completed: 'Imekamilika',
        cancelled: 'Imeghairiwa',
        paid: 'Imelipwa',
        estimated_total: 'Jumla Inayokadiriwa',

        // Car & House Rental
        rental_duration: 'Muda wa Kukodisha',
        pickup_date: 'Tarehe ya Kuchukua',
        return_date: 'Tarehe ya Kurudisha',
        checkin_date: 'Tarehe ya Kuingia',
        checkout_date: 'Tarehe ya Kutoka',
        seats: 'Viti',
        category: 'Kategoria',
        select_vehicle: 'Chagua Gari',
        select_property: 'Chagua Nyumba',
        stay_details: 'Maelezo ya Kukaa',
        find_home: 'Tafuta Nyumba ya Starehe',
        premium_fleet: 'Magari Yetu ya Kisasa',

        // About Us Detailed Content
        mission_title: 'Dhamira Yetu',
        mission_desc: 'Katika Me For You Advisory, dhamira yetu ni kurahisisha maisha yako, kufanya sherehe zako zisiweze kusahaulika, na safari zako zisiwe na mafadhaiko. Tunafanikisha hili kwa kutoa huduma za kiwango cha ulimwengu katika Matukio, Nyumba, na Usafiri, zinazotekelezwa kwa usahihi, ubunifu, na utunzaji. Lengo letu ni kutoa suluhisho zisizokuwa na mshono, za kitaalamu, na zilizobinafsishwa upatikanaji wa matarajio yako kila wakati.',
        background_title: 'Sisi ni Nani',
        background_desc: 'Me For You Advisory ni mshirika wako wa kitaalamu kwa Matukio, Nyumba, na Usafiri. Tunabadilisha mawazo kuwa uzoefu na changamoto kuwa suluhisho. Kwa kujitolea kwa taaluma, uaminifu, na ujanja, tunatoa huduma zinazorahisisha maisha yako, kufanya matukio yako yakumbukwe, na mipango yako isiwe na wasiwasi. Iwe unapanga harusi, kupata nyumba yako bora, au kupanga usafiri unaoaminika, tunahakikisha kuwa kila uzoefu hauna mshono, wa kufurahisha, na unaolingana na mahitaji yako.',
        founder_quote: 'Tunaongozwa na matokeo ya vitendo ambayo yanaunda athari ya maana. Mtazamo wetu ni kutoa matokeo halisi, yanayoweza kupimwa ambayo yanaleta mabadiliko katika maisha ya watu na mafanikio ya mashirika.',
        founder_full_name: 'Papy Patrick Ndazigaruye',
        value_professionalism: 'Utaalamu',
        value_professionalism_desc: 'Tunatekeleza kila kazi kwa ustadi, umakini kwa undani, na heshima, tukihakikisha huduma bora zaidi katika programu zetu zote.',
        value_trustworthiness: 'Uaminifu',
        value_trustworthiness_desc: 'Tunaheshimu ahadi zetu, kulinda maslahi yako, na kudumisha uwazi katika kila kitu tunachofanya.',
        value_smartness: 'Ujanja',
        value_smartness_desc: 'Tunaleta suluhisho za ubunifu, ufanisi, na uvumbuzi ambazo zinakuokoa wakati, juhudi, na rasilimali huku zikileta matokeo ya juu.',

        // Footer
        get_in_touch: 'Wasiliana Nasi',
        quick_links: 'Viungo vya Haraka',
        photo_gallery: 'Picha',
        hints_links: 'Vidokezo na Viungo',
        all_rights_reserved: 'Haki zote zimehifadhiwa.',
        privacy_policy: 'Sera ya Faragha',
        terms_condition: 'Vigezo na Masharti',

        // Forms
        full_name: 'Majina Kamili',
        email: 'Anwani ya Barua Pepe',
        password: 'Nenosiri',
        login_btn: 'Ingia',
        register_btn: 'Fungua Akaunti',
        forgot_password: 'Umesahau Nenosiri?',
        have_account: 'Tayari unayo akaunti?',
        no_account: 'Huna akaunti bado?',
        phone_number: 'Nambari ya Simu'
    },
    FR: {
        // Navigation & Common
        home: 'Accueil',
        about: 'À Propos',
        programs: 'Programmes',
        testimonials: 'Témoignages',
        contact: 'Contactez-nous',
        join_us: 'Rejoignez-nous',
        sign_in: 'Se Connecter',
        sign_up: 'S\'inscrire',
        sign_out: 'Se Déconnecter',
        dashboard: 'Tableau de bord',
        profile: 'Profil',
        bookings: 'Mes Réservations',
        account_settings: 'Paramètres du compte',
        control_dashboard: 'Tableau de bord de contrôle',
        manage_bookings: 'Gérer les réservations',
        our_story: 'Notre Histoire',
        our_team: 'Notre Équipe',
        partners: 'Partenaires',
        social_impact: 'Impact Social',
        help_center: 'Centre d\'aide',
        who_we_are: 'Qui Sommes-nous',
        our_network: 'Notre Réseau',
        support: 'Support',
        core_services: 'Nos Services de Base',
        highlights: 'Points Forts',
        events: 'Me For You Événements',
        housing: 'Me For You Logement',
        transport: 'Me For You Transport',
        cultural: 'Programmes Culturels',
        upcoming: 'À VENIR',
        new: 'NOUVEAU',
        currency: 'Devise',
        view_details: 'Voir les Détails',
        book_now: 'Réserver Maintenant',

        // Home Page
        hero_title_1: 'Services Premium pour Vos Besoins',
        hero_desc_1: 'Votre partenaire de confiance pour des événements inoubliables, des locations de voitures fiables et des hébergements confortables au Rwanda.',
        hero_title_2: 'Tout ce dont Vous Avez Besoin en un Seul Endroit',
        hero_desc_2: 'De la planification à l\'exécution, nous nous occupons de tout pour que vous puissiez profiter du moment en toute tranquillité.',
        hero_title_3: 'Expériences Culturelles Mémorables',
        hero_desc_3: 'Découvrez la riche histoire et les traditions du Rwanda grâce à nos visites guidées et événements communautaires.',
        hero_title_4: 'Séjours Confortables à Kigali',
        hero_desc_4: 'Des solutions de logement sécurisées et entièrement meublées conçues pour votre séjour professionnel ou personnel au cœur du Rwanda.',
        why_choose_us: 'Pourquoi Nous Choisir',
        why_choose_us_desc: 'Nous nous engageons à rendre vos événements spéciaux mémorables et à fournir des services de location de qualité supérieure pour votre commodité au Rwanda.',
        expert_team: 'Équipe d\'Experts',
        expert_team_desc: 'Notre équipe professionnelle apporte des années d\'expérience pour garantir l\'excellence dans chaque projet que nous entreprenons.',
        guaranteed_quality: 'Qualité Garantie',
        guaranteed_quality_desc: 'Nous privilégions la qualité et la satisfaction du client avant tout, en maintenant les normes de service les plus élevées.',
        client_centric: 'Centré sur le Client',
        client_centric_desc: 'Vos besoins sont notre priorité. Nous proposons des solutions sur mesure qui répondent parfaitement à vos attentes.',
        premium_services: 'Nos Services Premium',
        premium_services_desc: 'Découvrez une large gamme de services conçus pour vous faciliter la vie et rendre vos événements plus spectaculaires.',
        what_clients_say: 'Ce que Nos Clients Disent !',
        ready_to_hire: 'Prêt à Nous Engager pour Votre Événement ?',
        ready_to_hire_desc: 'Appelez-nous dès aujourd\'hui ou visitez notre bureau pour discuter de votre projet. Nous sommes prêts à donner vie à votre vision.',

        // Mobile App Section
        mobile_app_title: 'Applications Mobiles Me For You',
        mobile_app_subtitle: 'Améliorez Votre Expérience de Réservation',
        mobile_app_desc: 'Offrez une expérience numérique complète avec les applications mobiles Me For You riches en fonctionnalités pour les plateformes Android et iOS. Gérez vos réservations d\'événements, vérifiez la disponibilité des véhicules et trouvez des hébergements en déplacement.',
        mobile_app_android_ios: 'Applications Android et iOS',
        mobile_app_feature_desc: 'L\'application engage les utilisateurs avec une interface intuitive, des flux de travail logiques, des fonctionnalités interactives et des performances robustes.',
        explore_more: 'Explorer Plus',
        supercharge_success: 'Boostez votre succès avec les meilleures applications mobiles de leur catégorie',

        // Process Section
        process_title: 'Processus de planification et d\'exécution de projet',
        process_subtitle: 'Comment nous livrons l\'excellence pour chaque client',
        process_desc: 'Nous suivons une méthodologie structurée pour garantir que vos événements, vos besoins en logement et vos exigences de transport sont traités avec une précision professionnelle.',

        stage_1: 'Consultation',
        stage_1_p1: 'Briefing initial',
        stage_1_p2: 'Visite du site',
        stage_1_p3: 'Analyse budgétaire',
        stage_1_p4: 'Évaluation des besoins',
        stage_2: 'Stratégie',
        stage_2_p1: 'Sélection du lieu',
        stage_2_p2: 'Réseautage de fournisseurs',
        stage_2_p3: 'Conception de thèmes',
        stage_2_p4: 'Gestion du calendrier',
        stage_3: 'Exécution',
        stage_3_p1: 'Mise en œuvre du décor',
        stage_3_p2: 'Coordination logistique',
        stage_3_p3: 'Contrôle de la qualité',
        stage_3_p4: 'Suivi en direct',
        stage_4: 'Livraison finale',
        stage_4_p1: 'Succès de l\'événement',
        stage_4_p2: 'Collecte de commentaires',
        stage_4_p3: 'Soutien post-événement',
        stage_4_p4: 'Partenariat à long terme',

        lets_work_together: "Travaillons ensemble",

        // FAQ Section
        faq_title: 'Foire Aux Questions',
        faq_q1: 'Dois-je payer d\'avance pour les services de planification d\'événements ?',
        faq_a1: 'Nous exigeons généralement un dépôt d\'engagement pour sécuriser les fournisseurs et votre date préférée. Le solde restant peut être réglé selon un calendrier de paiement par étapes discuté lors de votre consultation.',
        faq_q2: 'Puis-je louer une voiture sans chauffeur professionnel ?',
        faq_a2: 'Oui, nous proposons des options d\'auto-conduite pour la majeure partie de notre flotte. Vous devrez fournir un permis de conduire valide et un dépôt de garantie. Alternativement, nos chauffeurs professionnels sont disponibles pour une expérience sans stress.',
        faq_q3: 'Quelles sont les conditions pour les locations de maisons à long terme ?',
        faq_a3: 'Pour les longs séjours (plus de 3 mois), nous exigeons un contrat de bail signé et un dépôt de garantie d\'un mois. Toutes nos propriétés sont entièrement meublées avec les services publics et la sécurité inclus.',
        faq_q4: 'Comment puis-je suivre l\'état de ma réservation ?',
        faq_a4: 'Une fois connecté à votre compte Me For You, vous pouvez accéder au tableau de bord "Mes Réservations". Ici, vous pouvez voir les mises à jour en temps réel sur l\'état de votre demande, l\'historique des paiements et les gestionnaires de services assignés.',
        faq_q5: 'Acceptez-vous les paiements par carte de crédit internationale ?',
        faq_a5: 'Absolument. Nous acceptons toutes les principales cartes de crédit/débit (Visa, MasterCard), ainsi que le Mobile Money local (MTN MoMo, Airtel Money) et les virements bancaires directs.',

        // Dashboard & Bookings
        recent_activity: 'Activité Récente',
        view_all: 'Tout Voir',
        no_bookings: 'Aucune réservation récente trouvée.',
        book_first: 'Réservez Votre Premier Service',
        quick_actions: 'Actions Rapides',
        plan_event: 'Planifier un Événement',
        rent_vehicle: 'Louer un Véhicule',
        find_house: 'Trouver une Maison',
        total_bookings: 'Total des Réservations',
        pending: 'En Attente',
        confirmed: 'Confirmé',
        total_spent: 'Total Dépensé',
        revenue: 'Revenus',
        id: 'ID',
        service: 'Service',
        date: 'Date',
        amount: 'Montant',
        status: 'Statut',
        completed: 'Terminé',
        cancelled: 'Annulé',
        paid: 'Payé',
        estimated_total: 'Total Estimé',

        // Car & House Rental
        rental_duration: 'Durée de Location',
        pickup_date: 'Date de Prise en Charge',
        return_date: 'Date de Retour',
        checkin_date: 'Date d\'Arrivée',
        checkout_date: 'Date de Départ',
        seats: 'Sièges',
        category: 'Catégorie',
        select_vehicle: 'Sélectionner le Véhicule',
        select_property: 'Sélectionner la Propriété',
        stay_details: 'Détails du Séjour',
        find_home: 'Trouvez Votre Chez-vous',
        premium_fleet: 'Notre Flotte Premium',

        // About Us Detailed Content
        mission_title: 'Notre Mission',
        mission_desc: 'Chez Me For You Advisory, notre mission est de vous faciliter la vie, de rendre vos célébrations inoubliables et vos voyages sans stress. Nous y parvenons en fournissant des services de classe mondiale dans les domaines des événements, du logement et du transport, exécutés avec précision, créativité et soin. Notre objectif est de fournir des solutions fluides, professionnelles et personnalisées qui dépassent vos attentes à chaque fois.',
        background_title: 'Qui Sommes-nous',
        background_desc: 'Me For You Advisory est votre compagnon professionnel pour les événements, le logement et le transport. Nous transformons les idées en expériences et les défis en solutions. Avec un engagement envers le professionnalisme, la fiabilité et l\'ingéniosité, nous fournissons des services qui vous facilitent la vie, rendent vos événements mémorables et vos projets sans souci. Qu\'il s\'agisse de planifier un mariage, de trouver votre maison idéale ou d\'organiser un transport fiable, nous veillons à ce que chaque expérience soit fluide, agréable et adaptée à vos besoins.',
        founder_quote: 'Nous sommes guidés par des résultats concrets qui créent un impact significatif. Notre objectif est de fournir des résultats réels et mesurables qui font une différence dans la vie des gens et le succès des organisations.',
        founder_full_name: 'Papy Patrick Ndazigaruye',
        value_professionalism: 'Professionnalisme',
        value_professionalism_desc: 'Nous exécutons chaque tâche avec compétence, attention aux détails et respect, garantissant un service de qualité supérieure dans tous nos programmes.',
        value_trustworthiness: 'Fiabilité',
        value_trustworthiness_desc: 'Nous honorons nos engagements, protégeons vos intérêts et maintenons la transparence dans tout ce que nous faisons.',
        value_smartness: 'Ingéniosité',
        value_smartness_desc: 'Nous apportons des solutions créatives, efficaces et innovantes qui vous font gagner du temps, de l\'effort et des ressources tout en produisant un impact maximal.',

        // Footer
        get_in_touch: 'Contactez-nous',
        quick_links: 'Liens Rapides',
        photo_gallery: 'Galerie Photo',
        hints_links: 'Conseils & Liens',
        all_rights_reserved: 'Tous droits réservés.',
        privacy_policy: 'Politique de Confidentialité',
        terms_condition: 'Termes et Conditions',

        // Forms
        full_name: 'Nom Complet',
        email: 'Adresse E-mail',
        password: 'Mot de passe',
        login_btn: 'Se Connecter',
        register_btn: 'Créer un Compte',
        forgot_password: 'Mot de passe oublié ?',
        have_account: 'Vous avez déjà un compte ?',
        no_account: 'Vous n\'avez pas encore de compte ?',
        phone_number: 'Numéro de Téléphone'
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved as Language) || 'EN';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || translations['EN'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
